version: "3"

services:
  mysql:
    build: ./docker/mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: spark_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql:/var/log/mysql
